/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as JsScriptDotjsRouteImport } from './routes/js/script[.]js'
import { Route as GuidesSplatRouteImport } from './routes/guides/$'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as BlogsSplatRouteImport } from './routes/blogs/$'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as ApiEventRouteImport } from './routes/api/event'
import { Route as ApiBacklinkCheckRouteImport } from './routes/api/backlink-check'
import { Route as MarketingSupportRouteImport } from './routes/_marketing/support'
import { Route as MarketingRoadmapRouteImport } from './routes/_marketing/roadmap'
import { Route as MarketingPricingRouteImport } from './routes/_marketing/pricing'
import { Route as MarketingOpenSourceSeoRouteImport } from './routes/_marketing/open-source-seo'
import { Route as MarketingGoogleSearchConsoleMcpRouteImport } from './routes/_marketing/google-search-console-mcp'
import { Route as MarketingBacklinkCheckerRouteImport } from './routes/_marketing/backlink-checker'
import { Route as MarketingLibraryIndexRouteImport } from './routes/_marketing/library/index'
import { Route as MarketingFeaturesIndexRouteImport } from './routes/_marketing/features/index'
import { Route as MarketingFeaturesSiteAuditRouteImport } from './routes/_marketing/features/site-audit'
import { Route as MarketingFeaturesSavedKeywordsRouteImport } from './routes/_marketing/features/saved-keywords'
import { Route as MarketingFeaturesRankTrackingRouteImport } from './routes/_marketing/features/rank-tracking'
import { Route as MarketingFeaturesMcpRouteImport } from './routes/_marketing/features/mcp'
import { Route as MarketingFeaturesKeywordResearchRouteImport } from './routes/_marketing/features/keyword-research'
import { Route as MarketingFeaturesDomainOverviewRouteImport } from './routes/_marketing/features/domain-overview'
import { Route as MarketingFeaturesBacklinksRouteImport } from './routes/_marketing/features/backlinks'
import { Route as MarketingFeaturesBacklinkCheckerRouteImport } from './routes/_marketing/features/backlink-checker'
import { Route as MarketingFeaturesAiSearchPromptsRouteImport } from './routes/_marketing/features/ai-search-prompts'
import { Route as MarketingFeaturesAiBrandVisibilityRouteImport } from './routes/_marketing/features/ai-brand-visibility'
import { Route as MarketingLibraryKeywordResearchIndexRouteImport } from './routes/_marketing/library/keyword-research/index'
import { Route as MarketingLibraryCompetitiveAnalysisIndexRouteImport } from './routes/_marketing/library/competitive-analysis/index'
import { Route as MarketingLibraryKeywordResearchSeedFromConversationRouteImport } from './routes/_marketing/library/keyword-research/seed-from-conversation'
import { Route as MarketingLibraryKeywordResearchSearchIntentMappingRouteImport } from './routes/_marketing/library/keyword-research/search-intent-mapping'
import { Route as MarketingLibraryKeywordResearchPositioningToDemandRouteImport } from './routes/_marketing/library/keyword-research/positioning-to-demand'
import { Route as MarketingLibraryKeywordResearchOpportunitySizingForecastingRouteImport } from './routes/_marketing/library/keyword-research/opportunity-sizing-forecasting'
import { Route as MarketingLibraryKeywordResearchLongTailQuestionMiningRouteImport } from './routes/_marketing/library/keyword-research/long-tail-question-mining'
import { Route as MarketingLibraryKeywordResearchIntentBeyondGoogleRouteImport } from './routes/_marketing/library/keyword-research/intent-beyond-google'
import { Route as MarketingLibraryKeywordResearchGscProgrammaticDiscoveryRouteImport } from './routes/_marketing/library/keyword-research/gsc-programmatic-discovery'
import { Route as MarketingLibraryKeywordResearchClusterTopicalHubsRouteImport } from './routes/_marketing/library/keyword-research/cluster-topical-hubs'
import { Route as MarketingLibraryCompetitiveAnalysisKeywordGapAnalysisRouteImport } from './routes/_marketing/library/competitive-analysis/keyword-gap-analysis'
import { Route as MarketingLibraryCompetitiveAnalysisFindYourRealCompetitorsRouteImport } from './routes/_marketing/library/competitive-analysis/find-your-real-competitors'
import { Route as MarketingLibraryCompetitiveAnalysisCompetitorTrafficEstimatesRouteImport } from './routes/_marketing/library/competitive-analysis/competitor-traffic-estimates'
import { Route as MarketingLibraryCompetitiveAnalysisBacklinkGapAnalysisRouteImport } from './routes/_marketing/library/competitive-analysis/backlink-gap-analysis'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const JsScriptDotjsRoute = JsScriptDotjsRouteImport.update({
  id: '/js/script.js',
  path: '/js/script.js',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSplatRoute = GuidesSplatRouteImport.update({
  id: '/guides/$',
  path: '/guides/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSplatRoute = BlogsSplatRouteImport.update({
  id: '/blogs/$',
  path: '/blogs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventRoute = ApiEventRouteImport.update({
  id: '/api/event',
  path: '/api/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBacklinkCheckRoute = ApiBacklinkCheckRouteImport.update({
  id: '/api/backlink-check',
  path: '/api/backlink-check',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingSupportRoute = MarketingSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingRoadmapRoute = MarketingRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingOpenSourceSeoRoute = MarketingOpenSourceSeoRouteImport.update({
  id: '/open-source-seo',
  path: '/open-source-seo',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingGoogleSearchConsoleMcpRoute =
  MarketingGoogleSearchConsoleMcpRouteImport.update({
    id: '/google-search-console-mcp',
    path: '/google-search-console-mcp',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingBacklinkCheckerRoute =
  MarketingBacklinkCheckerRouteImport.update({
    id: '/backlink-checker',
    path: '/backlink-checker',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryIndexRoute = MarketingLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFeaturesIndexRoute = MarketingFeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFeaturesSiteAuditRoute =
  MarketingFeaturesSiteAuditRouteImport.update({
    id: '/features/site-audit',
    path: '/features/site-audit',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingFeaturesSavedKeywordsRoute =
  MarketingFeaturesSavedKeywordsRouteImport.update({
    id: '/features/saved-keywords',
    path: '/features/saved-keywords',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingFeaturesRankTrackingRoute =
  MarketingFeaturesRankTrackingRouteImport.update({
    id: '/features/rank-tracking',
    path: '/features/rank-tracking',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingFeaturesMcpRoute = MarketingFeaturesMcpRouteImport.update({
  id: '/features/mcp',
  path: '/features/mcp',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFeaturesKeywordResearchRoute =
  MarketingFeaturesKeywordResearchRouteImport.update({
    id: '/features/keyword-research',
    path: '/features/keyword-research',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingFeaturesDomainOverviewRoute =
  MarketingFeaturesDomainOverviewRouteImport.update({
    id: '/features/domain-overview',
    path: '/features/domain-overview',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingFeaturesBacklinksRoute =
  MarketingFeaturesBacklinksRouteImport.update({
    id: '/features/backlinks',
    path: '/features/backlinks',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingFeaturesBacklinkCheckerRoute =
  MarketingFeaturesBacklinkCheckerRouteImport.update({
    id: '/features/backlink-checker',
    path: '/features/backlink-checker',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingFeaturesAiSearchPromptsRoute =
  MarketingFeaturesAiSearchPromptsRouteImport.update({
    id: '/features/ai-search-prompts',
    path: '/features/ai-search-prompts',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingFeaturesAiBrandVisibilityRoute =
  MarketingFeaturesAiBrandVisibilityRouteImport.update({
    id: '/features/ai-brand-visibility',
    path: '/features/ai-brand-visibility',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryKeywordResearchIndexRoute =
  MarketingLibraryKeywordResearchIndexRouteImport.update({
    id: '/library/keyword-research/',
    path: '/library/keyword-research/',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryCompetitiveAnalysisIndexRoute =
  MarketingLibraryCompetitiveAnalysisIndexRouteImport.update({
    id: '/library/competitive-analysis/',
    path: '/library/competitive-analysis/',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryKeywordResearchSeedFromConversationRoute =
  MarketingLibraryKeywordResearchSeedFromConversationRouteImport.update({
    id: '/library/keyword-research/seed-from-conversation',
    path: '/library/keyword-research/seed-from-conversation',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryKeywordResearchSearchIntentMappingRoute =
  MarketingLibraryKeywordResearchSearchIntentMappingRouteImport.update({
    id: '/library/keyword-research/search-intent-mapping',
    path: '/library/keyword-research/search-intent-mapping',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryKeywordResearchPositioningToDemandRoute =
  MarketingLibraryKeywordResearchPositioningToDemandRouteImport.update({
    id: '/library/keyword-research/positioning-to-demand',
    path: '/library/keyword-research/positioning-to-demand',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryKeywordResearchOpportunitySizingForecastingRoute =
  MarketingLibraryKeywordResearchOpportunitySizingForecastingRouteImport.update(
    {
      id: '/library/keyword-research/opportunity-sizing-forecasting',
      path: '/library/keyword-research/opportunity-sizing-forecasting',
      getParentRoute: () => MarketingRoute,
    } as any,
  )
const MarketingLibraryKeywordResearchLongTailQuestionMiningRoute =
  MarketingLibraryKeywordResearchLongTailQuestionMiningRouteImport.update({
    id: '/library/keyword-research/long-tail-question-mining',
    path: '/library/keyword-research/long-tail-question-mining',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryKeywordResearchIntentBeyondGoogleRoute =
  MarketingLibraryKeywordResearchIntentBeyondGoogleRouteImport.update({
    id: '/library/keyword-research/intent-beyond-google',
    path: '/library/keyword-research/intent-beyond-google',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryKeywordResearchGscProgrammaticDiscoveryRoute =
  MarketingLibraryKeywordResearchGscProgrammaticDiscoveryRouteImport.update({
    id: '/library/keyword-research/gsc-programmatic-discovery',
    path: '/library/keyword-research/gsc-programmatic-discovery',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryKeywordResearchClusterTopicalHubsRoute =
  MarketingLibraryKeywordResearchClusterTopicalHubsRouteImport.update({
    id: '/library/keyword-research/cluster-topical-hubs',
    path: '/library/keyword-research/cluster-topical-hubs',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryCompetitiveAnalysisKeywordGapAnalysisRoute =
  MarketingLibraryCompetitiveAnalysisKeywordGapAnalysisRouteImport.update({
    id: '/library/competitive-analysis/keyword-gap-analysis',
    path: '/library/competitive-analysis/keyword-gap-analysis',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryCompetitiveAnalysisFindYourRealCompetitorsRoute =
  MarketingLibraryCompetitiveAnalysisFindYourRealCompetitorsRouteImport.update({
    id: '/library/competitive-analysis/find-your-real-competitors',
    path: '/library/competitive-analysis/find-your-real-competitors',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryCompetitiveAnalysisCompetitorTrafficEstimatesRoute =
  MarketingLibraryCompetitiveAnalysisCompetitorTrafficEstimatesRouteImport.update(
    {
      id: '/library/competitive-analysis/competitor-traffic-estimates',
      path: '/library/competitive-analysis/competitor-traffic-estimates',
      getParentRoute: () => MarketingRoute,
    } as any,
  )
const MarketingLibraryCompetitiveAnalysisBacklinkGapAnalysisRoute =
  MarketingLibraryCompetitiveAnalysisBacklinkGapAnalysisRouteImport.update({
    id: '/library/competitive-analysis/backlink-gap-analysis',
    path: '/library/competitive-analysis/backlink-gap-analysis',
    getParentRoute: () => MarketingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/backlink-checker': typeof MarketingBacklinkCheckerRoute
  '/google-search-console-mcp': typeof MarketingGoogleSearchConsoleMcpRoute
  '/open-source-seo': typeof MarketingOpenSourceSeoRoute
  '/pricing': typeof MarketingPricingRoute
  '/roadmap': typeof MarketingRoadmapRoute
  '/support': typeof MarketingSupportRoute
  '/api/backlink-check': typeof ApiBacklinkCheckRoute
  '/api/event': typeof ApiEventRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/blogs/$': typeof BlogsSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/guides/$': typeof GuidesSplatRoute
  '/js/script.js': typeof JsScriptDotjsRoute
  '/blogs/': typeof BlogsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/features/ai-brand-visibility': typeof MarketingFeaturesAiBrandVisibilityRoute
  '/features/ai-search-prompts': typeof MarketingFeaturesAiSearchPromptsRoute
  '/features/backlink-checker': typeof MarketingFeaturesBacklinkCheckerRoute
  '/features/backlinks': typeof MarketingFeaturesBacklinksRoute
  '/features/domain-overview': typeof MarketingFeaturesDomainOverviewRoute
  '/features/keyword-research': typeof MarketingFeaturesKeywordResearchRoute
  '/features/mcp': typeof MarketingFeaturesMcpRoute
  '/features/rank-tracking': typeof MarketingFeaturesRankTrackingRoute
  '/features/saved-keywords': typeof MarketingFeaturesSavedKeywordsRoute
  '/features/site-audit': typeof MarketingFeaturesSiteAuditRoute
  '/features/': typeof MarketingFeaturesIndexRoute
  '/library/': typeof MarketingLibraryIndexRoute
  '/library/competitive-analysis/backlink-gap-analysis': typeof MarketingLibraryCompetitiveAnalysisBacklinkGapAnalysisRoute
  '/library/competitive-analysis/competitor-traffic-estimates': typeof MarketingLibraryCompetitiveAnalysisCompetitorTrafficEstimatesRoute
  '/library/competitive-analysis/find-your-real-competitors': typeof MarketingLibraryCompetitiveAnalysisFindYourRealCompetitorsRoute
  '/library/competitive-analysis/keyword-gap-analysis': typeof MarketingLibraryCompetitiveAnalysisKeywordGapAnalysisRoute
  '/library/keyword-research/cluster-topical-hubs': typeof MarketingLibraryKeywordResearchClusterTopicalHubsRoute
  '/library/keyword-research/gsc-programmatic-discovery': typeof MarketingLibraryKeywordResearchGscProgrammaticDiscoveryRoute
  '/library/keyword-research/intent-beyond-google': typeof MarketingLibraryKeywordResearchIntentBeyondGoogleRoute
  '/library/keyword-research/long-tail-question-mining': typeof MarketingLibraryKeywordResearchLongTailQuestionMiningRoute
  '/library/keyword-research/opportunity-sizing-forecasting': typeof MarketingLibraryKeywordResearchOpportunitySizingForecastingRoute
  '/library/keyword-research/positioning-to-demand': typeof MarketingLibraryKeywordResearchPositioningToDemandRoute
  '/library/keyword-research/search-intent-mapping': typeof MarketingLibraryKeywordResearchSearchIntentMappingRoute
  '/library/keyword-research/seed-from-conversation': typeof MarketingLibraryKeywordResearchSeedFromConversationRoute
  '/library/competitive-analysis/': typeof MarketingLibraryCompetitiveAnalysisIndexRoute
  '/library/keyword-research/': typeof MarketingLibraryKeywordResearchIndexRoute
}
export interface FileRoutesByTo {
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/backlink-checker': typeof MarketingBacklinkCheckerRoute
  '/google-search-console-mcp': typeof MarketingGoogleSearchConsoleMcpRoute
  '/open-source-seo': typeof MarketingOpenSourceSeoRoute
  '/pricing': typeof MarketingPricingRoute
  '/roadmap': typeof MarketingRoadmapRoute
  '/support': typeof MarketingSupportRoute
  '/api/backlink-check': typeof ApiBacklinkCheckRoute
  '/api/event': typeof ApiEventRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/blogs/$': typeof BlogsSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/guides/$': typeof GuidesSplatRoute
  '/js/script.js': typeof JsScriptDotjsRoute
  '/': typeof MarketingIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/docs': typeof DocsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/features/ai-brand-visibility': typeof MarketingFeaturesAiBrandVisibilityRoute
  '/features/ai-search-prompts': typeof MarketingFeaturesAiSearchPromptsRoute
  '/features/backlink-checker': typeof MarketingFeaturesBacklinkCheckerRoute
  '/features/backlinks': typeof MarketingFeaturesBacklinksRoute
  '/features/domain-overview': typeof MarketingFeaturesDomainOverviewRoute
  '/features/keyword-research': typeof MarketingFeaturesKeywordResearchRoute
  '/features/mcp': typeof MarketingFeaturesMcpRoute
  '/features/rank-tracking': typeof MarketingFeaturesRankTrackingRoute
  '/features/saved-keywords': typeof MarketingFeaturesSavedKeywordsRoute
  '/features/site-audit': typeof MarketingFeaturesSiteAuditRoute
  '/features': typeof MarketingFeaturesIndexRoute
  '/library': typeof MarketingLibraryIndexRoute
  '/library/competitive-analysis/backlink-gap-analysis': typeof MarketingLibraryCompetitiveAnalysisBacklinkGapAnalysisRoute
  '/library/competitive-analysis/competitor-traffic-estimates': typeof MarketingLibraryCompetitiveAnalysisCompetitorTrafficEstimatesRoute
  '/library/competitive-analysis/find-your-real-competitors': typeof MarketingLibraryCompetitiveAnalysisFindYourRealCompetitorsRoute
  '/library/competitive-analysis/keyword-gap-analysis': typeof MarketingLibraryCompetitiveAnalysisKeywordGapAnalysisRoute
  '/library/keyword-research/cluster-topical-hubs': typeof MarketingLibraryKeywordResearchClusterTopicalHubsRoute
  '/library/keyword-research/gsc-programmatic-discovery': typeof MarketingLibraryKeywordResearchGscProgrammaticDiscoveryRoute
  '/library/keyword-research/intent-beyond-google': typeof MarketingLibraryKeywordResearchIntentBeyondGoogleRoute
  '/library/keyword-research/long-tail-question-mining': typeof MarketingLibraryKeywordResearchLongTailQuestionMiningRoute
  '/library/keyword-research/opportunity-sizing-forecasting': typeof MarketingLibraryKeywordResearchOpportunitySizingForecastingRoute
  '/library/keyword-research/positioning-to-demand': typeof MarketingLibraryKeywordResearchPositioningToDemandRoute
  '/library/keyword-research/search-intent-mapping': typeof MarketingLibraryKeywordResearchSearchIntentMappingRoute
  '/library/keyword-research/seed-from-conversation': typeof MarketingLibraryKeywordResearchSeedFromConversationRoute
  '/library/competitive-analysis': typeof MarketingLibraryCompetitiveAnalysisIndexRoute
  '/library/keyword-research': typeof MarketingLibraryKeywordResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/_marketing/backlink-checker': typeof MarketingBacklinkCheckerRoute
  '/_marketing/google-search-console-mcp': typeof MarketingGoogleSearchConsoleMcpRoute
  '/_marketing/open-source-seo': typeof MarketingOpenSourceSeoRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/roadmap': typeof MarketingRoadmapRoute
  '/_marketing/support': typeof MarketingSupportRoute
  '/api/backlink-check': typeof ApiBacklinkCheckRoute
  '/api/event': typeof ApiEventRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/blogs/$': typeof BlogsSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/guides/$': typeof GuidesSplatRoute
  '/js/script.js': typeof JsScriptDotjsRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/_marketing/features/ai-brand-visibility': typeof MarketingFeaturesAiBrandVisibilityRoute
  '/_marketing/features/ai-search-prompts': typeof MarketingFeaturesAiSearchPromptsRoute
  '/_marketing/features/backlink-checker': typeof MarketingFeaturesBacklinkCheckerRoute
  '/_marketing/features/backlinks': typeof MarketingFeaturesBacklinksRoute
  '/_marketing/features/domain-overview': typeof MarketingFeaturesDomainOverviewRoute
  '/_marketing/features/keyword-research': typeof MarketingFeaturesKeywordResearchRoute
  '/_marketing/features/mcp': typeof MarketingFeaturesMcpRoute
  '/_marketing/features/rank-tracking': typeof MarketingFeaturesRankTrackingRoute
  '/_marketing/features/saved-keywords': typeof MarketingFeaturesSavedKeywordsRoute
  '/_marketing/features/site-audit': typeof MarketingFeaturesSiteAuditRoute
  '/_marketing/features/': typeof MarketingFeaturesIndexRoute
  '/_marketing/library/': typeof MarketingLibraryIndexRoute
  '/_marketing/library/competitive-analysis/backlink-gap-analysis': typeof MarketingLibraryCompetitiveAnalysisBacklinkGapAnalysisRoute
  '/_marketing/library/competitive-analysis/competitor-traffic-estimates': typeof MarketingLibraryCompetitiveAnalysisCompetitorTrafficEstimatesRoute
  '/_marketing/library/competitive-analysis/find-your-real-competitors': typeof MarketingLibraryCompetitiveAnalysisFindYourRealCompetitorsRoute
  '/_marketing/library/competitive-analysis/keyword-gap-analysis': typeof MarketingLibraryCompetitiveAnalysisKeywordGapAnalysisRoute
  '/_marketing/library/keyword-research/cluster-topical-hubs': typeof MarketingLibraryKeywordResearchClusterTopicalHubsRoute
  '/_marketing/library/keyword-research/gsc-programmatic-discovery': typeof MarketingLibraryKeywordResearchGscProgrammaticDiscoveryRoute
  '/_marketing/library/keyword-research/intent-beyond-google': typeof MarketingLibraryKeywordResearchIntentBeyondGoogleRoute
  '/_marketing/library/keyword-research/long-tail-question-mining': typeof MarketingLibraryKeywordResearchLongTailQuestionMiningRoute
  '/_marketing/library/keyword-research/opportunity-sizing-forecasting': typeof MarketingLibraryKeywordResearchOpportunitySizingForecastingRoute
  '/_marketing/library/keyword-research/positioning-to-demand': typeof MarketingLibraryKeywordResearchPositioningToDemandRoute
  '/_marketing/library/keyword-research/search-intent-mapping': typeof MarketingLibraryKeywordResearchSearchIntentMappingRoute
  '/_marketing/library/keyword-research/seed-from-conversation': typeof MarketingLibraryKeywordResearchSeedFromConversationRoute
  '/_marketing/library/competitive-analysis/': typeof MarketingLibraryCompetitiveAnalysisIndexRoute
  '/_marketing/library/keyword-research/': typeof MarketingLibraryKeywordResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms-and-conditions'
    | '/backlink-checker'
    | '/google-search-console-mcp'
    | '/open-source-seo'
    | '/pricing'
    | '/roadmap'
    | '/support'
    | '/api/backlink-check'
    | '/api/event'
    | '/api/subscribe'
    | '/blogs/$'
    | '/docs/$'
    | '/guides/$'
    | '/js/script.js'
    | '/blogs/'
    | '/docs/'
    | '/guides/'
    | '/features/ai-brand-visibility'
    | '/features/ai-search-prompts'
    | '/features/backlink-checker'
    | '/features/backlinks'
    | '/features/domain-overview'
    | '/features/keyword-research'
    | '/features/mcp'
    | '/features/rank-tracking'
    | '/features/saved-keywords'
    | '/features/site-audit'
    | '/features/'
    | '/library/'
    | '/library/competitive-analysis/backlink-gap-analysis'
    | '/library/competitive-analysis/competitor-traffic-estimates'
    | '/library/competitive-analysis/find-your-real-competitors'
    | '/library/competitive-analysis/keyword-gap-analysis'
    | '/library/keyword-research/cluster-topical-hubs'
    | '/library/keyword-research/gsc-programmatic-discovery'
    | '/library/keyword-research/intent-beyond-google'
    | '/library/keyword-research/long-tail-question-mining'
    | '/library/keyword-research/opportunity-sizing-forecasting'
    | '/library/keyword-research/positioning-to-demand'
    | '/library/keyword-research/search-intent-mapping'
    | '/library/keyword-research/seed-from-conversation'
    | '/library/competitive-analysis/'
    | '/library/keyword-research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/privacy'
    | '/terms-and-conditions'
    | '/backlink-checker'
    | '/google-search-console-mcp'
    | '/open-source-seo'
    | '/pricing'
    | '/roadmap'
    | '/support'
    | '/api/backlink-check'
    | '/api/event'
    | '/api/subscribe'
    | '/blogs/$'
    | '/docs/$'
    | '/guides/$'
    | '/js/script.js'
    | '/'
    | '/blogs'
    | '/docs'
    | '/guides'
    | '/features/ai-brand-visibility'
    | '/features/ai-search-prompts'
    | '/features/backlink-checker'
    | '/features/backlinks'
    | '/features/domain-overview'
    | '/features/keyword-research'
    | '/features/mcp'
    | '/features/rank-tracking'
    | '/features/saved-keywords'
    | '/features/site-audit'
    | '/features'
    | '/library'
    | '/library/competitive-analysis/backlink-gap-analysis'
    | '/library/competitive-analysis/competitor-traffic-estimates'
    | '/library/competitive-analysis/find-your-real-competitors'
    | '/library/competitive-analysis/keyword-gap-analysis'
    | '/library/keyword-research/cluster-topical-hubs'
    | '/library/keyword-research/gsc-programmatic-discovery'
    | '/library/keyword-research/intent-beyond-google'
    | '/library/keyword-research/long-tail-question-mining'
    | '/library/keyword-research/opportunity-sizing-forecasting'
    | '/library/keyword-research/positioning-to-demand'
    | '/library/keyword-research/search-intent-mapping'
    | '/library/keyword-research/seed-from-conversation'
    | '/library/competitive-analysis'
    | '/library/keyword-research'
  id:
    | '__root__'
    | '/_marketing'
    | '/privacy'
    | '/terms-and-conditions'
    | '/_marketing/backlink-checker'
    | '/_marketing/google-search-console-mcp'
    | '/_marketing/open-source-seo'
    | '/_marketing/pricing'
    | '/_marketing/roadmap'
    | '/_marketing/support'
    | '/api/backlink-check'
    | '/api/event'
    | '/api/subscribe'
    | '/blogs/$'
    | '/docs/$'
    | '/guides/$'
    | '/js/script.js'
    | '/_marketing/'
    | '/blogs/'
    | '/docs/'
    | '/guides/'
    | '/_marketing/features/ai-brand-visibility'
    | '/_marketing/features/ai-search-prompts'
    | '/_marketing/features/backlink-checker'
    | '/_marketing/features/backlinks'
    | '/_marketing/features/domain-overview'
    | '/_marketing/features/keyword-research'
    | '/_marketing/features/mcp'
    | '/_marketing/features/rank-tracking'
    | '/_marketing/features/saved-keywords'
    | '/_marketing/features/site-audit'
    | '/_marketing/features/'
    | '/_marketing/library/'
    | '/_marketing/library/competitive-analysis/backlink-gap-analysis'
    | '/_marketing/library/competitive-analysis/competitor-traffic-estimates'
    | '/_marketing/library/competitive-analysis/find-your-real-competitors'
    | '/_marketing/library/competitive-analysis/keyword-gap-analysis'
    | '/_marketing/library/keyword-research/cluster-topical-hubs'
    | '/_marketing/library/keyword-research/gsc-programmatic-discovery'
    | '/_marketing/library/keyword-research/intent-beyond-google'
    | '/_marketing/library/keyword-research/long-tail-question-mining'
    | '/_marketing/library/keyword-research/opportunity-sizing-forecasting'
    | '/_marketing/library/keyword-research/positioning-to-demand'
    | '/_marketing/library/keyword-research/search-intent-mapping'
    | '/_marketing/library/keyword-research/seed-from-conversation'
    | '/_marketing/library/competitive-analysis/'
    | '/_marketing/library/keyword-research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ApiBacklinkCheckRoute: typeof ApiBacklinkCheckRoute
  ApiEventRoute: typeof ApiEventRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  BlogsSplatRoute: typeof BlogsSplatRoute
  DocsSplatRoute: typeof DocsSplatRoute
  GuidesSplatRoute: typeof GuidesSplatRoute
  JsScriptDotjsRoute: typeof JsScriptDotjsRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/js/script.js': {
      id: '/js/script.js'
      path: '/js/script.js'
      fullPath: '/js/script.js'
      preLoaderRoute: typeof JsScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$': {
      id: '/guides/$'
      path: '/guides/$'
      fullPath: '/guides/$'
      preLoaderRoute: typeof GuidesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$': {
      id: '/blogs/$'
      path: '/blogs/$'
      fullPath: '/blogs/$'
      preLoaderRoute: typeof BlogsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/event': {
      id: '/api/event'
      path: '/api/event'
      fullPath: '/api/event'
      preLoaderRoute: typeof ApiEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backlink-check': {
      id: '/api/backlink-check'
      path: '/api/backlink-check'
      fullPath: '/api/backlink-check'
      preLoaderRoute: typeof ApiBacklinkCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/support': {
      id: '/_marketing/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof MarketingSupportRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/roadmap': {
      id: '/_marketing/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof MarketingRoadmapRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/open-source-seo': {
      id: '/_marketing/open-source-seo'
      path: '/open-source-seo'
      fullPath: '/open-source-seo'
      preLoaderRoute: typeof MarketingOpenSourceSeoRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/google-search-console-mcp': {
      id: '/_marketing/google-search-console-mcp'
      path: '/google-search-console-mcp'
      fullPath: '/google-search-console-mcp'
      preLoaderRoute: typeof MarketingGoogleSearchConsoleMcpRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/backlink-checker': {
      id: '/_marketing/backlink-checker'
      path: '/backlink-checker'
      fullPath: '/backlink-checker'
      preLoaderRoute: typeof MarketingBacklinkCheckerRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/': {
      id: '/_marketing/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof MarketingLibraryIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/': {
      id: '/_marketing/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof MarketingFeaturesIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/site-audit': {
      id: '/_marketing/features/site-audit'
      path: '/features/site-audit'
      fullPath: '/features/site-audit'
      preLoaderRoute: typeof MarketingFeaturesSiteAuditRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/saved-keywords': {
      id: '/_marketing/features/saved-keywords'
      path: '/features/saved-keywords'
      fullPath: '/features/saved-keywords'
      preLoaderRoute: typeof MarketingFeaturesSavedKeywordsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/rank-tracking': {
      id: '/_marketing/features/rank-tracking'
      path: '/features/rank-tracking'
      fullPath: '/features/rank-tracking'
      preLoaderRoute: typeof MarketingFeaturesRankTrackingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/mcp': {
      id: '/_marketing/features/mcp'
      path: '/features/mcp'
      fullPath: '/features/mcp'
      preLoaderRoute: typeof MarketingFeaturesMcpRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/keyword-research': {
      id: '/_marketing/features/keyword-research'
      path: '/features/keyword-research'
      fullPath: '/features/keyword-research'
      preLoaderRoute: typeof MarketingFeaturesKeywordResearchRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/domain-overview': {
      id: '/_marketing/features/domain-overview'
      path: '/features/domain-overview'
      fullPath: '/features/domain-overview'
      preLoaderRoute: typeof MarketingFeaturesDomainOverviewRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/backlinks': {
      id: '/_marketing/features/backlinks'
      path: '/features/backlinks'
      fullPath: '/features/backlinks'
      preLoaderRoute: typeof MarketingFeaturesBacklinksRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/backlink-checker': {
      id: '/_marketing/features/backlink-checker'
      path: '/features/backlink-checker'
      fullPath: '/features/backlink-checker'
      preLoaderRoute: typeof MarketingFeaturesBacklinkCheckerRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/ai-search-prompts': {
      id: '/_marketing/features/ai-search-prompts'
      path: '/features/ai-search-prompts'
      fullPath: '/features/ai-search-prompts'
      preLoaderRoute: typeof MarketingFeaturesAiSearchPromptsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/ai-brand-visibility': {
      id: '/_marketing/features/ai-brand-visibility'
      path: '/features/ai-brand-visibility'
      fullPath: '/features/ai-brand-visibility'
      preLoaderRoute: typeof MarketingFeaturesAiBrandVisibilityRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/keyword-research/': {
      id: '/_marketing/library/keyword-research/'
      path: '/library/keyword-research'
      fullPath: '/library/keyword-research/'
      preLoaderRoute: typeof MarketingLibraryKeywordResearchIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/competitive-analysis/': {
      id: '/_marketing/library/competitive-analysis/'
      path: '/library/competitive-analysis'
      fullPath: '/library/competitive-analysis/'
      preLoaderRoute: typeof MarketingLibraryCompetitiveAnalysisIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/keyword-research/seed-from-conversation': {
      id: '/_marketing/library/keyword-research/seed-from-conversation'
      path: '/library/keyword-research/seed-from-conversation'
      fullPath: '/library/keyword-research/seed-from-conversation'
      preLoaderRoute: typeof MarketingLibraryKeywordResearchSeedFromConversationRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/keyword-research/search-intent-mapping': {
      id: '/_marketing/library/keyword-research/search-intent-mapping'
      path: '/library/keyword-research/search-intent-mapping'
      fullPath: '/library/keyword-research/search-intent-mapping'
      preLoaderRoute: typeof MarketingLibraryKeywordResearchSearchIntentMappingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/keyword-research/positioning-to-demand': {
      id: '/_marketing/library/keyword-research/positioning-to-demand'
      path: '/library/keyword-research/positioning-to-demand'
      fullPath: '/library/keyword-research/positioning-to-demand'
      preLoaderRoute: typeof MarketingLibraryKeywordResearchPositioningToDemandRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/keyword-research/opportunity-sizing-forecasting': {
      id: '/_marketing/library/keyword-research/opportunity-sizing-forecasting'
      path: '/library/keyword-research/opportunity-sizing-forecasting'
      fullPath: '/library/keyword-research/opportunity-sizing-forecasting'
      preLoaderRoute: typeof MarketingLibraryKeywordResearchOpportunitySizingForecastingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/keyword-research/long-tail-question-mining': {
      id: '/_marketing/library/keyword-research/long-tail-question-mining'
      path: '/library/keyword-research/long-tail-question-mining'
      fullPath: '/library/keyword-research/long-tail-question-mining'
      preLoaderRoute: typeof MarketingLibraryKeywordResearchLongTailQuestionMiningRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/keyword-research/intent-beyond-google': {
      id: '/_marketing/library/keyword-research/intent-beyond-google'
      path: '/library/keyword-research/intent-beyond-google'
      fullPath: '/library/keyword-research/intent-beyond-google'
      preLoaderRoute: typeof MarketingLibraryKeywordResearchIntentBeyondGoogleRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/keyword-research/gsc-programmatic-discovery': {
      id: '/_marketing/library/keyword-research/gsc-programmatic-discovery'
      path: '/library/keyword-research/gsc-programmatic-discovery'
      fullPath: '/library/keyword-research/gsc-programmatic-discovery'
      preLoaderRoute: typeof MarketingLibraryKeywordResearchGscProgrammaticDiscoveryRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/keyword-research/cluster-topical-hubs': {
      id: '/_marketing/library/keyword-research/cluster-topical-hubs'
      path: '/library/keyword-research/cluster-topical-hubs'
      fullPath: '/library/keyword-research/cluster-topical-hubs'
      preLoaderRoute: typeof MarketingLibraryKeywordResearchClusterTopicalHubsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/competitive-analysis/keyword-gap-analysis': {
      id: '/_marketing/library/competitive-analysis/keyword-gap-analysis'
      path: '/library/competitive-analysis/keyword-gap-analysis'
      fullPath: '/library/competitive-analysis/keyword-gap-analysis'
      preLoaderRoute: typeof MarketingLibraryCompetitiveAnalysisKeywordGapAnalysisRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/competitive-analysis/find-your-real-competitors': {
      id: '/_marketing/library/competitive-analysis/find-your-real-competitors'
      path: '/library/competitive-analysis/find-your-real-competitors'
      fullPath: '/library/competitive-analysis/find-your-real-competitors'
      preLoaderRoute: typeof MarketingLibraryCompetitiveAnalysisFindYourRealCompetitorsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/competitive-analysis/competitor-traffic-estimates': {
      id: '/_marketing/library/competitive-analysis/competitor-traffic-estimates'
      path: '/library/competitive-analysis/competitor-traffic-estimates'
      fullPath: '/library/competitive-analysis/competitor-traffic-estimates'
      preLoaderRoute: typeof MarketingLibraryCompetitiveAnalysisCompetitorTrafficEstimatesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/competitive-analysis/backlink-gap-analysis': {
      id: '/_marketing/library/competitive-analysis/backlink-gap-analysis'
      path: '/library/competitive-analysis/backlink-gap-analysis'
      fullPath: '/library/competitive-analysis/backlink-gap-analysis'
      preLoaderRoute: typeof MarketingLibraryCompetitiveAnalysisBacklinkGapAnalysisRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingBacklinkCheckerRoute: typeof MarketingBacklinkCheckerRoute
  MarketingGoogleSearchConsoleMcpRoute: typeof MarketingGoogleSearchConsoleMcpRoute
  MarketingOpenSourceSeoRoute: typeof MarketingOpenSourceSeoRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingRoadmapRoute: typeof MarketingRoadmapRoute
  MarketingSupportRoute: typeof MarketingSupportRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingFeaturesAiBrandVisibilityRoute: typeof MarketingFeaturesAiBrandVisibilityRoute
  MarketingFeaturesAiSearchPromptsRoute: typeof MarketingFeaturesAiSearchPromptsRoute
  MarketingFeaturesBacklinkCheckerRoute: typeof MarketingFeaturesBacklinkCheckerRoute
  MarketingFeaturesBacklinksRoute: typeof MarketingFeaturesBacklinksRoute
  MarketingFeaturesDomainOverviewRoute: typeof MarketingFeaturesDomainOverviewRoute
  MarketingFeaturesKeywordResearchRoute: typeof MarketingFeaturesKeywordResearchRoute
  MarketingFeaturesMcpRoute: typeof MarketingFeaturesMcpRoute
  MarketingFeaturesRankTrackingRoute: typeof MarketingFeaturesRankTrackingRoute
  MarketingFeaturesSavedKeywordsRoute: typeof MarketingFeaturesSavedKeywordsRoute
  MarketingFeaturesSiteAuditRoute: typeof MarketingFeaturesSiteAuditRoute
  MarketingFeaturesIndexRoute: typeof MarketingFeaturesIndexRoute
  MarketingLibraryIndexRoute: typeof MarketingLibraryIndexRoute
  MarketingLibraryCompetitiveAnalysisBacklinkGapAnalysisRoute: typeof MarketingLibraryCompetitiveAnalysisBacklinkGapAnalysisRoute
  MarketingLibraryCompetitiveAnalysisCompetitorTrafficEstimatesRoute: typeof MarketingLibraryCompetitiveAnalysisCompetitorTrafficEstimatesRoute
  MarketingLibraryCompetitiveAnalysisFindYourRealCompetitorsRoute: typeof MarketingLibraryCompetitiveAnalysisFindYourRealCompetitorsRoute
  MarketingLibraryCompetitiveAnalysisKeywordGapAnalysisRoute: typeof MarketingLibraryCompetitiveAnalysisKeywordGapAnalysisRoute
  MarketingLibraryKeywordResearchClusterTopicalHubsRoute: typeof MarketingLibraryKeywordResearchClusterTopicalHubsRoute
  MarketingLibraryKeywordResearchGscProgrammaticDiscoveryRoute: typeof MarketingLibraryKeywordResearchGscProgrammaticDiscoveryRoute
  MarketingLibraryKeywordResearchIntentBeyondGoogleRoute: typeof MarketingLibraryKeywordResearchIntentBeyondGoogleRoute
  MarketingLibraryKeywordResearchLongTailQuestionMiningRoute: typeof MarketingLibraryKeywordResearchLongTailQuestionMiningRoute
  MarketingLibraryKeywordResearchOpportunitySizingForecastingRoute: typeof MarketingLibraryKeywordResearchOpportunitySizingForecastingRoute
  MarketingLibraryKeywordResearchPositioningToDemandRoute: typeof MarketingLibraryKeywordResearchPositioningToDemandRoute
  MarketingLibraryKeywordResearchSearchIntentMappingRoute: typeof MarketingLibraryKeywordResearchSearchIntentMappingRoute
  MarketingLibraryKeywordResearchSeedFromConversationRoute: typeof MarketingLibraryKeywordResearchSeedFromConversationRoute
  MarketingLibraryCompetitiveAnalysisIndexRoute: typeof MarketingLibraryCompetitiveAnalysisIndexRoute
  MarketingLibraryKeywordResearchIndexRoute: typeof MarketingLibraryKeywordResearchIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingBacklinkCheckerRoute: MarketingBacklinkCheckerRoute,
  MarketingGoogleSearchConsoleMcpRoute: MarketingGoogleSearchConsoleMcpRoute,
  MarketingOpenSourceSeoRoute: MarketingOpenSourceSeoRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingRoadmapRoute: MarketingRoadmapRoute,
  MarketingSupportRoute: MarketingSupportRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingFeaturesAiBrandVisibilityRoute:
    MarketingFeaturesAiBrandVisibilityRoute,
  MarketingFeaturesAiSearchPromptsRoute: MarketingFeaturesAiSearchPromptsRoute,
  MarketingFeaturesBacklinkCheckerRoute: MarketingFeaturesBacklinkCheckerRoute,
  MarketingFeaturesBacklinksRoute: MarketingFeaturesBacklinksRoute,
  MarketingFeaturesDomainOverviewRoute: MarketingFeaturesDomainOverviewRoute,
  MarketingFeaturesKeywordResearchRoute: MarketingFeaturesKeywordResearchRoute,
  MarketingFeaturesMcpRoute: MarketingFeaturesMcpRoute,
  MarketingFeaturesRankTrackingRoute: MarketingFeaturesRankTrackingRoute,
  MarketingFeaturesSavedKeywordsRoute: MarketingFeaturesSavedKeywordsRoute,
  MarketingFeaturesSiteAuditRoute: MarketingFeaturesSiteAuditRoute,
  MarketingFeaturesIndexRoute: MarketingFeaturesIndexRoute,
  MarketingLibraryIndexRoute: MarketingLibraryIndexRoute,
  MarketingLibraryCompetitiveAnalysisBacklinkGapAnalysisRoute:
    MarketingLibraryCompetitiveAnalysisBacklinkGapAnalysisRoute,
  MarketingLibraryCompetitiveAnalysisCompetitorTrafficEstimatesRoute:
    MarketingLibraryCompetitiveAnalysisCompetitorTrafficEstimatesRoute,
  MarketingLibraryCompetitiveAnalysisFindYourRealCompetitorsRoute:
    MarketingLibraryCompetitiveAnalysisFindYourRealCompetitorsRoute,
  MarketingLibraryCompetitiveAnalysisKeywordGapAnalysisRoute:
    MarketingLibraryCompetitiveAnalysisKeywordGapAnalysisRoute,
  MarketingLibraryKeywordResearchClusterTopicalHubsRoute:
    MarketingLibraryKeywordResearchClusterTopicalHubsRoute,
  MarketingLibraryKeywordResearchGscProgrammaticDiscoveryRoute:
    MarketingLibraryKeywordResearchGscProgrammaticDiscoveryRoute,
  MarketingLibraryKeywordResearchIntentBeyondGoogleRoute:
    MarketingLibraryKeywordResearchIntentBeyondGoogleRoute,
  MarketingLibraryKeywordResearchLongTailQuestionMiningRoute:
    MarketingLibraryKeywordResearchLongTailQuestionMiningRoute,
  MarketingLibraryKeywordResearchOpportunitySizingForecastingRoute:
    MarketingLibraryKeywordResearchOpportunitySizingForecastingRoute,
  MarketingLibraryKeywordResearchPositioningToDemandRoute:
    MarketingLibraryKeywordResearchPositioningToDemandRoute,
  MarketingLibraryKeywordResearchSearchIntentMappingRoute:
    MarketingLibraryKeywordResearchSearchIntentMappingRoute,
  MarketingLibraryKeywordResearchSeedFromConversationRoute:
    MarketingLibraryKeywordResearchSeedFromConversationRoute,
  MarketingLibraryCompetitiveAnalysisIndexRoute:
    MarketingLibraryCompetitiveAnalysisIndexRoute,
  MarketingLibraryKeywordResearchIndexRoute:
    MarketingLibraryKeywordResearchIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ApiBacklinkCheckRoute: ApiBacklinkCheckRoute,
  ApiEventRoute: ApiEventRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  BlogsSplatRoute: BlogsSplatRoute,
  DocsSplatRoute: DocsSplatRoute,
  GuidesSplatRoute: GuidesSplatRoute,
  JsScriptDotjsRoute: JsScriptDotjsRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
